
class ErrorStatus(object):
    UNEXPECTED_ERROR = 1
    STORE_IS_CLOSED = 2
    INTERNAL_ERROR = 3
    ORDER_NOT_FOUND = 4
    MENU_ERROR = 5
    UNAVAILABLE_PRODUCT = 6
    DIFFERENT_VALUES = 7
    ERROR_PRODUCING = 8
    FISCAL_ERROR = 9
    LOGISTIC_ERROR = 10
    MANUAL_CANCEL = 11
