# MAKEFILE
COMPDIR=$(CURDIR)

all:
	@python -m pip install -r requirements.txt -t lib --extra-index-url=https://pip.e-deploy.com.br/
	@rm -rf $(COMPDIR)/nohup.out
	$(info $@: Done!)

clean:
	rm -rf $(COMPDIR)/lib
	rm -rf $(COMPDIR)/dev_lib
	rm -rf $(COMPDIR)/nohup.out
	$(info $@: Done!)