class NfceNamespaces:
    nfe = "http://www.portalfiscal.inf.br/nfe"
    NAMESPACE_SOAP = "http://www.w3.org/2003/05/soap-envelope"
    NAMESPACE_AUTORIZACAO = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao"
    NAMESPACE_AUTORIZACAO_3 = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3"
    NAMESPACE_RET_AUTORIZACAO = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao"
    NAMESPACE_RET_INUTILIZACAO_2 = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeInutilizacao2"
    NAMESPACE_RET_AUTORIZACAO_3 = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao3"
    NAMESPACE_CONSULTA = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao"
    NAMESPACE_CONSULTA_SITUACAO = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2"
    NAMESPACE_XMLDSIG = "http://www.w3.org/2000/09/xmldsig#"