# Configurable variables
STANDARD_DATA_DIR := ../datas/data.client
STANDARD_COMMON_DIR := $(STANDARD_DATA_DIR)/server/common
OUTPUT_PLATFORMS := linux-redhat-x86_64 windows-x86

OPSYS=$(shell uname -s)
BASEDIR=$(CURDIR)/..
ifeq ($(OPSYS),Linux)
	OPSYS := linux-redhat
	PLATFORM := windows-x86
	APACHEDIR=/etc/httpd
else
	OPSYS := windows
	PLATFORM := windows-x86
	MAKE := $(CURDIR)/tools/make.exe
	APACHEDIR=$(BASEDIR)/apache
endif

# Build Rules
.PHONY: all clean

all: sdkcore sdkcore-syslink apache-conf post-install
	$(info $@: Done!)

sdkcore:
	@if [ -d ../mwsdk ]; then rm -rf ../mwsdk; fi
	python -m pip install mwsdk==2.0.94 -t ../ --extra-index-url=http://mwsdk.hmledp.com.br/ --no-cache-dir --trusted-host mwsdk.hmledp.com.br

ifeq ($(OPSYS),windows)
sdkcore-syslink:
else
sdkcore-syslink:
	ln -s ../mwsdk/linux-x86_64 ../mwsdk/linux-centos-x86_64
endif

common-comp:
	if [ -e $(BASEDIR)/src/common.mk ]; then \
		cd ../src && $(MAKE) -f $(BASEDIR)/src/common.mk && cd -; \
	fi
	$(info $@: Done!)

ifeq ($(OPSYS),windows)
apache-conf:
	@rm -rf httpd-2.4.41-win64-VS16.zip
	@if [ -d $(APACHEDIR) ]; then rm -rf $(APACHEDIR); fi
	curl -LO https://s3.amazonaws.com/pos-install.e-deploy.com.br/httpd-2.4.41-win64-VS16.zip
	@rm -rf temp
	unzip -q httpd-2.4.41-win64-VS16.zip -d temp
	@mkdir $(APACHEDIR)
	@cp -a temp/Apache24/* $(APACHEDIR)
	@rm -rf temp
else
apache-conf:
endif
	sed -i.bak 's,^\(Define SRVROOT \)".*",\1"$(APACHEDIR)",g' $(APACHEDIR)/conf/httpd.conf
	sed -i.bak 's,^\(DocumentRoot \)".*htdocs",\1"$(BASEDIR)/datas/server/htdocs",g' $(APACHEDIR)/conf/httpd.conf
	sed -i.bak 's,^\(<Directory \)".*htdocs"\(>\),\1"$(BASEDIR)/datas/server/htdocs"\2,g' $(APACHEDIR)/conf/httpd.conf
	sed -i.bak 's,^\(Listen \).*,\18080,g' $(APACHEDIR)/conf/httpd.conf
	sed -i.bak 's,^#\(LoadModule proxy_module modules/mod_proxy.so\),\1,g' $(APACHEDIR)/conf/httpd.conf
	sed -i.bak 's,^#\(LoadModule proxy_http_module modules/mod_proxy_http.so\),\1,g' $(APACHEDIR)/conf/httpd.conf
	sed -i.bak 's,^\(<Directory \/>\),ProxyTimeout 60000000\nProxyPreserveHost On\nProxyPass /mwapp http://127.0.0.1:9494/mwapp\nProxyPassReverse /mwapp http://127.0.0.1:9494/mwapp\n\n\1,g' $(APACHEDIR)/conf/httpd.conf
	$(info $@: Done!)

post-install: common-comp
	@if [ ! -d $(BASEDIR)/datas/server/htdocs ]; then mkdir $(BASEDIR)/datas/server/htdocs; fi
	cd ../src/_guizip && find -name '*.zip' -exec sh -c 'unzip -o -d "$(BASEDIR)/datas/server/htdocs/$${1%.*}" "$$1"' _  {} \; && cd -

# Clean Rules
clean-common:
	if [ -e $(BASEDIR)/src/common.mk ]; then \
		cd ../src && $(MAKE) clean -f $(BASEDIR)/src/common.mk && cd -; \
	fi
	$(info $@: Done!)

clean-apache:
	if [ -d httpd-2.4.41-win64-VS16.zip ]; then rm httpd-2.4.41-win64-VS16.zip; fi
	if [ -d $(APACHEDIR) ]; then rm -rf $(APACHEDIR); fi
	$(info $@: Done!)

clean: clean-common clean-apache
	@if [ -d ../mwsdk ]; then rm -rf ../mwsdk*; fi
	$(info $@: Done!)
