export default [
  {
    name: 'DEFAULT',

    recalledCellBackground: '#8a2eb2',
    voidedCellBackground: '#696969',
    voidedIconColor: '#a80100',
    alertCellBackground: '#696969',
    alertIconColor: '#d3b800',
    saveIconColor: '#58a3f8',
    backgroundColor: '#ffffff',
    fontColor: '#000',
    expoFontColor: '#000',
    expoActiveFontColor: '#fff',
    defaultBorder: '0.2vmin solid gray',
    activeBackgroundColor: '#000',
    activeFontColor: '#fff',
    tabBackgroundColor: '#d3d3d3',
    expoCellColor: '#d3d3d3',
    expoDefaultColor: '#bababa',
    activeExpoCellColor: '#484848',
    expoHeaderCellColor: '#c0c0c0',
    activeExpoHeaderCellColor: '#484848',
    expoFooterCellColor: '#c0c0c0',
    activeExpoFooterCellColor: '#484848',
    noItemsCellColor: '#FFEBB2',
    expoCellBorder: '0.4vmin solid',
    disabledIconColor: '#c1bfbf',
    pickupOrderBox: '#fff',
    buttonColor: 'lightgreen',
    activeButtonColor: '#fff',
    defaultMargin: '1vmin',
    blinkColor: '#7D1480',
    pickupOrderColor: '#b10931',
    pickupBackgroundColor: '#e8e8e8',
    pickupReadyOrderColor: '#00B1A8',
    pickupCalledOrderColor: '#ffad4d',
    pickupFontFamily: 'BlockCFFCon',
    deliveryColorBorder: 'transparent',
    deliveryColorFont: 'none',
    takeOutColorBorder: 'transparent',
    takeOutColorFont: 'none',
    animDuration: '1s'
  }
]
